# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  database: library_development
  username: root
  password: usman
  host: localhost
test:
  adapter: mysql2
  database: library_test
  username: root
  password: usman
  host: localhost
production:
  adapter: mysql2
  database: library_production
  username: root
  password: usman
  host: localhost